### ISSUE TITLE
What breaks if/when third party cookies go away?

### ISSUE THREAD

**Issue by samuelgoto** [WICG/WebID#34]
Here are a few things that comes to mind:

# button personalization (e.g. profile picture)

For example:

![](https://images.squarespace-cdn.com/content/v1/5ac3325c36099b0503c61815/1524439286701-AKX9BZWES0FCKP7UWTUE/ke17ZwdGBToddI8pDm48kPpcqHJCvqSfGpsZv2dp_pFZw-zPPgdn4jUwVcJE1ZvWQUxwkmyExglNqGp0IvTJZUJFbgE-7XRK3dMEBRBhUpztBQXB6M46eOr6pjxcgq74b0z-dlJ90n-ndB8tANEd56dg0kjKz19RmZ00y6ipIs4/image-asset.png)

And here is for google's sign-in:

![](https://developers.google.com/identity/one-tap/web/images/one-tap.png)

# auto sign-in 

TODO(goto): gather links

Anything else we are forgetting? Anything in enterprise or EDU?

**Comment by asr-enid** [comment]
Session Discovery  - https://github.com/WICG/WebID/issues/14

**Comment by samuelgoto** [comment]
I'm going to resolve this thread here now that I have written down what we expect to break (and have a place to learn more).

https://github.com/WICG/WebID/blob/main/cookies.md
