### ISSUE TITLE
.php extension should not appear in .well-known URLs

### ISSUE THREAD

**Issue by jeremyroman** [WICG/WebID#63]
`cookies.md` uses `.well-known` URLs ending in `.php`. Well-known URLs shouldn't assume a particular server-side technology like PHP. In this case they should probably be extensionless.

**Comment by kenrb** [comment]
Thanks for pointing that out. Elsewhere here and in our prototype code those endpoint URLs are obtained from `.well-known/webid`, and would not be expected to contain `.well-known` in the path. That might be more detail than Sam is intending to convey on that page but I'll change the paths to make it clearer.
